#pragma config(Sensor, S3, colourSensor, sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

task main()
{
  string sColour;

  while (true) {
    switch (SensorValue[colourSensor])
    {
      case BLACKCOLOR:
      	sColour = "Black";
      	break;
      case BLUECOLOR:
      	sColour = "Blue";
      	break;
      case GREENCOLOR:
      	sColour = "Green";
      	break;
      case YELLOWCOLOR:
      	sColour = "Yellow";
      	break;
      case REDCOLOR:
      	sColour = "Red";
      	break;
      case WHITECOLOR:
      	sColour = "White";
      	break;
      default:
      	sColour = "???";
      	break;
    }
    nxtDisplayCenteredTextLine(2, sColour);
    wait1Msec(50);
  }
}
